<a href="https://colab.research.google.com/github/Mint0511/Data-analytics/blob/main/lab2_NguyenVanMinh_3122410242%20/%20slide_03_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **DATA ANALYTICS AND VISUALIZATION WITH PYTHON**

**NUMPY**

In [3]:
# Tạo danh sách Python
v = list(range(1, 6))  # Tạo list: [1, 2, 3, 4, 5]
print(v)

[1, 2, 3, 4, 5]


In [4]:
# Nhân list với 2
print(2 * v)  # [1,2,3,4,5,1,2,3,4,5] → Python list nhân với số → lặp lại danh sách

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [5]:
# Dùng NumPy để tạo mảng
import numpy as np
v = np.arange(1, 6)  # Tạo numpy array: [1 2 3 4 5]
print(v)

[1 2 3 4 5]


In [6]:
# Nhân mảng với 2
print(2 * v)  # [ 2  4  6  8 10 ] → NumPy array nhân với số → nhân từng phần tử

[ 2  4  6  8 10]


**PYTHON DATA STRUCTURES**

In [7]:
# Python Collections

fruits = ["apple", "banana", "cherry"]      # List: có thứ tự, thay đổi được, cho phép trùng lặp
colors = ("red", "green", "blue")           # Tuple: có thứ tự, không thay đổi được, cho phép trùng lặp
animals = {'cat', 'dog'}                    # Set: không có thứ tự, không trùng lặp, không thay đổi được
person = {"name": "Tom", "age": 20}         # Dictionary: key-value, có thứ tự (Python 3.7+), key không trùng lặp


**`List[]`**

In [8]:
# Tạo list
x = [60, 70, 80, 90]

# Độ dài của list
print(len(x))   # 4 → có 4 phần tử

# Truy cập phần tử theo chỉ số
print(x[0])     # 60 → phần tử đầu tiên
print(x[1])     # 70 → phần tử thứ hai
print(x[-1])    # 90 → phần tử cuối cùng (dùng chỉ số âm)


4
60
70
90


**NUMPY CREATE ARRAY**

In [9]:
#1
import numpy as np

# Tạo 2 mảng NumPy
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Nhân từng phần tử
c = a * b
print(c)  # Output: [ 4 10 18 ]


[ 4 10 18]


In [10]:
#2
import numpy as np

a = np.zeros((2,2))           # Mảng 2x2 toàn số 0 → [[0. 0.]
                               #                      [0. 0.]]
print(a)

b = np.ones((1,2))            # Mảng 1x2 toàn số 1 → [[1. 1.]]
print(b)

c = np.full((2,2), 7)         # Mảng 2x2 toàn số 7 → [[7 7]
                               #                      [7 7]]
print(c)

d = np.eye(2)                 # Ma trận đơn vị 2x2 → [[1. 0.]
                               #                      [0. 1.]]
print(d)

e = np.random.random((2,2))   # Mảng 2x2 số ngẫu nhiên, ví dụ in ra: [[0.37454012 0.95071431]
                               #                                      [0.73199394 0.59865848]]
print(e)


[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.3280482  0.99918131]
 [0.60220415 0.26822014]]


In [11]:
#3
import numpy as np

a = np.arange(15).reshape(3, 5)   # np.arange(15) → [0,1,2,...,14], reshape(3,5) → 3 hàng 5 cột
print(a)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [12]:
print(a.shape)      # Kích thước mảng → (3, 5) → 3 hàng, 5 cột

(3, 5)


In [13]:
print(a.ndim)       # Số chiều của mảng → 2 (2D array)

2


In [14]:
print(a.dtype.name) # Kiểu dữ liệu của phần tử → 'int64' hoặc 'int32' tùy hệ thống

int64


**NUMPY ndarrray: MULTIDIMENSIANAL ARRAY OBJECT**

*One - dimensional Array (1-D Array)*

In [15]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])  # Tạo numpy array 1D từ list Python
print(a)                        # In mảng ra: [1 2 3 4 5]


[1 2 3 4 5]


*Two-dimensional Array (2-D Array)*

In [16]:
#tạo một mảng NumPy 2 chiều 4x5
import numpy as np

a = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])  # Tạo mảng 2D 4 hàng, 5 cột

print(a)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [17]:
#tạo một mảng NumPy 2 chiều 3x4
import numpy as np

a = np.array([
    [0, 1, 2, 3],
    [10, 11, 12, 13],
    [20, 21, 22, 23]
])  # Mảng 2D 3 hàng, 4 cột

print(a)


[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]


In [18]:
print(a.ndim)       # Số chiều của mảng → 2 (2D array)

2


In [19]:
print(a.shape)      # Kích thước mảng → (3, 4) → 3 hàng, 4 cột

(3, 4)


**PANDAS**

*Creating pd.DataFrame* : tạo một DataFrame bằng pandas



In [20]:
import pandas as pd

df = pd.DataFrame(
    {
        "a": [4, 5, 6],   # cột a
        "b": [7, 8, 9],   # cột b
        "c": [10, 11, 12] # cột c
    },
    index=[1, 2, 3]       # đặt chỉ số hàng là 1, 2, 3
)

print(df)


   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12


In [22]:
print(type(df)) #dùng để kiểm tra kiểu dữ liệu của đối tượng df

<class 'pandas.core.frame.DataFrame'>


*import các thư viện Python phổ biến:*

In [ ]:
import numpy as np          # thư viện xử lý mảng và tính toán số học
import pandas as pd         # thư viện xử lý dữ liệu dạng bảng (DataFrame)
import matplotlib.pyplot as plt  # thư viện vẽ đồ thị 2D

print('pandas imported')   # in thông báo

*Tạo một pandas Series, tức là một mảng 1 chiều có nhãn (index):*

In [23]:
import numpy as np
import pandas as pd

s = pd.Series([1, 3, 5, np.nan, 6, 8])  # Tạo Series 1D với giá trị NaN
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


*tạo một chuỗi các ngày liên tiếp (DatetimeIndex) trong pandas:*

In [24]:
import pandas as pd

dates = pd.date_range('20181001', periods=6)  # Tạo 6 ngày liên tiếp từ 1/10/2018
print(dates)


DatetimeIndex(['2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
               '2018-10-05', '2018-10-06'],
              dtype='datetime64[ns]', freq='D')


*Tạo một DataFrame 6x4 với số ngẫu nhiên, sử dụng dates làm index và A,B,C,D làm tên cột:*

In [25]:
import numpy as np
import pandas as pd

dates = pd.date_range('20181001', periods=6)          # 6 ngày liên tiếp
df = pd.DataFrame(
    np.random.randn(6,4),                             # mảng 6x4 số ngẫu nhiên theo chuẩn Gaussian
    index=dates,                                      # đặt index là ngày
    columns=list('ABCD')                              # đặt tên cột là A, B, C, D
)

print(df)


                   A         B         C         D
2018-10-01  0.420142  0.488045 -0.054783  0.106483
2018-10-02  2.398920  1.408621  0.398770 -0.056719
2018-10-03 -0.057262  1.052898 -0.591571 -0.048362
2018-10-04  0.618580 -1.720417 -1.102944  0.524941
2018-10-05  0.957799  0.551558 -0.831278  0.477363
2018-10-06 -1.395034  0.931376  0.650433  0.434298


*Tạo một DataFrame 3x5 với số ngẫu nhiên, dùng tên học sinh làm index và A, B, C, D, E làm cột:*

In [26]:
import numpy as np
import pandas as pd

df = pd.DataFrame(
    np.random.randn(3,5),                    # mảng 3x5 số ngẫu nhiên theo chuẩn Gaussian
    index=['student1','student2','student3'], # tên hàng là học sinh
    columns=list('ABCDE')                     # tên cột là A, B, C, D, E
)

print(df)


                 A         B         C         D         E
student1  1.872237  1.073776 -0.027718 -1.444828 -0.595844
student2  0.345859 -0.551706  0.861977  0.869571  1.044340
student3  0.767862  1.033611  1.160316 -1.107440  0.339227


*Tạo một DataFrame pandas với nhiều kiểu dữ liệu khác nhau:*

In [27]:
import numpy as np
import pandas as pd

df2 = pd.DataFrame({
    'A': 1.,                                  # float
    'B': pd.Timestamp('20181001'),            # kiểu datetime
    'C': pd.Series(2.5, index=list(range(4)), dtype='float32'),  # Series float32
    'D': np.array([3]*4, dtype='int32'),      # mảng int32
    'E': pd.Categorical(["test","train","test","train"]), # Categorical
    'F': 'foo'                                # string
})

print(df2)


     A          B    C  D      E    F
0  1.0 2018-10-01  2.5  3   test  foo
1  1.0 2018-10-01  2.5  3  train  foo
2  1.0 2018-10-01  2.5  3   test  foo
3  1.0 2018-10-01  2.5  3  train  foo


In [28]:
df2.dtypes  # Kiểm tra kiểu dữ liệu từng cột


A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

**PYTHON FINANCE APPLICATION WITH PANDAS**

*Tạo một sổ cái đơn giản bằng pandas để quản lý các giao dịch tài chính, cho phép thêm giao dịch, xem sổ, và tính số dư hiện tại:*

In [29]:
import pandas as pd

# Tạo DataFrame để lưu các giao dịch
columns = ['Date', 'Description', 'Amount']
ledger = pd.DataFrame(columns=columns)  # DataFrame rỗng với các cột Date, Description, Amount

# Hàm thêm giao dịch vào sổ
def add_transaction(date, description, amount):
    global ledger
    new_transaction = pd.DataFrame([[date, description, amount]], columns=columns)  # Tạo 1 DataFrame 1 hàng
    ledger = pd.concat([ledger, new_transaction], ignore_index=True)  # Nối vào ledger, reset index

# Hàm xem sổ giao dịch
def view_ledger():
    print(ledger)  # In toàn bộ ledger

# Hàm tính số dư hiện tại
def get_balance():
    return ledger['Amount'].sum()  # Tổng cột Amount

# Thêm các giao dịch mẫu
add_transaction('2023-11-01', 'Income', 1000)       # Thu nhập +1000
add_transaction('2023-11-02', 'Groceries', -200)    # Chi tiêu -200
add_transaction('2023-11-03', 'Utilities', -100)    # Chi tiêu -100

# Xem sổ giao dịch
view_ledger()

# Kiểm tra số dư hiện tại
print("Current Balance:", get_balance())  # Output: 700


         Date Description Amount
0  2023-11-01      Income   1000
1  2023-11-02   Groceries   -200
2  2023-11-03   Utilities   -100
Current Balance: 700
