<a href="https://colab.research.google.com/github/Mint0511/Data-analytics/blob/main/lab2_NguyenVanMinh_3122410242%20/%20slide_03_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **DATA ANALYTICS AND VISUALIZATION WITH PYTHON**

**NUMPY**

In [3]:
# Tạo danh sách Python
v = list(range(1, 6))  # Tạo list: [1, 2, 3, 4, 5]
print(v)

[1, 2, 3, 4, 5]


In [4]:
# Nhân list với 2
print(2 * v)  # [1,2,3,4,5,1,2,3,4,5] → Python list nhân với số → lặp lại danh sách

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [5]:
# Dùng NumPy để tạo mảng
import numpy as np
v = np.arange(1, 6)  # Tạo numpy array: [1 2 3 4 5]
print(v)

[1 2 3 4 5]


In [6]:
# Nhân mảng với 2
print(2 * v)  # [ 2  4  6  8 10 ] → NumPy array nhân với số → nhân từng phần tử

[ 2  4  6  8 10]


**PYTHON DATA STRUCTURES**

In [7]:
# Python Collections

fruits = ["apple", "banana", "cherry"]      # List: có thứ tự, thay đổi được, cho phép trùng lặp
colors = ("red", "green", "blue")           # Tuple: có thứ tự, không thay đổi được, cho phép trùng lặp
animals = {'cat', 'dog'}                    # Set: không có thứ tự, không trùng lặp, không thay đổi được
person = {"name": "Tom", "age": 20}         # Dictionary: key-value, có thứ tự (Python 3.7+), key không trùng lặp


**`List[]`**

In [8]:
# Tạo list
x = [60, 70, 80, 90]

# Độ dài của list
print(len(x))   # 4 → có 4 phần tử

# Truy cập phần tử theo chỉ số
print(x[0])     # 60 → phần tử đầu tiên
print(x[1])     # 70 → phần tử thứ hai
print(x[-1])    # 90 → phần tử cuối cùng (dùng chỉ số âm)


4
60
70
90


**NUMPY CREATE ARRAY**

In [9]:
import numpy as np

# Tạo 2 mảng NumPy
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Nhân từng phần tử
c = a * b
print(c)  # Output: [ 4 10 18 ]


[ 4 10 18]


In [10]:
import numpy as np

a = np.zeros((2,2))           # Mảng 2x2 toàn số 0 → [[0. 0.]
                               #                      [0. 0.]]
print(a)

b = np.ones((1,2))            # Mảng 1x2 toàn số 1 → [[1. 1.]]
print(b)

c = np.full((2,2), 7)         # Mảng 2x2 toàn số 7 → [[7 7]
                               #                      [7 7]]
print(c)

d = np.eye(2)                 # Ma trận đơn vị 2x2 → [[1. 0.]
                               #                      [0. 1.]]
print(d)

e = np.random.random((2,2))   # Mảng 2x2 số ngẫu nhiên, ví dụ in ra: [[0.37454012 0.95071431]
                               #                                      [0.73199394 0.59865848]]
print(e)


[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.3280482  0.99918131]
 [0.60220415 0.26822014]]
